name: PR Check

on:
  pull_request:
    branches: [ '*' ]
    paths-ignore:
    - '**/*.md'
    - .gitignore
env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust Toolchain
        run: |
          rustup toolchain install nightly
          rustup default nightly
          
      - name: cargo check
        run: cargo check